import { expect, test, type Locator, type Page } from "@playwright/test";

const pageUrl = process.env.COURSE_GUI_BASE_URL;
if (!pageUrl) throw new Error("COURSE_GUI_BASE_URL is required.");

const validUser = { username: "Valid_User7", email: "valid.user7@example.com", password: "CoursePass9", dateOfBirth: "2000-02-29" };
const username = (page: Page) => page.getByLabel(/^username/i);
const email = (page: Page) => page.getByLabel(/email/i);
const dateOfBirth = (page: Page) => page.getByLabel(/date of birth/i);
const password = (page: Page) => page.getByLabel(/^password(?!.*confirm)/i);
const confirmation = (page: Page) => page.getByLabel(/confirm.*password|password.*confirm/i);
const terms = (page: Page) => page.getByRole("checkbox", { name: /terms|service|agree|accept/i });
const submit = (page: Page) => page.getByRole("button", { name: /register|create account|sign up|submit/i });
const toggle = (page: Page) => page.getByRole("button", { name: /show.*password|hide.*password/i }).or(page.getByRole("checkbox", { name: /show.*password|hide.*password/i }));
async function open(page: Page) { await page.goto(pageUrl!); }
async function fillValid(page: Page, overrides: Partial<typeof validUser> = {}) {
  const user = { ...validUser, ...overrides }; await username(page).fill(user.username); await email(page).fill(user.email); await dateOfBirth(page).fill(user.dateOfBirth); await password(page).fill(user.password); await confirmation(page).fill(user.password); await terms(page).check();
}
async function expectSuccess(page: Page) { await expect(page.getByText(/success|account.{0,30}created|registered|welcome/i).last()).toBeVisible(); }
async function expectFieldError(control: Locator) {
  await expect(control).toHaveAttribute("aria-invalid", "true"); const describedBy = await control.getAttribute("aria-describedby"); expect(describedBy).toBeTruthy();
  const ids = describedBy!.split(/\s+/).filter(Boolean); const texts = await Promise.all(ids.map(id => control.page().locator(`#${id}`).textContent())); expect(texts.some(value => Boolean(value?.trim()))).toBe(true);
}
test.beforeEach(async ({ page }) => { await open(page); });

test("[Structure and accessibility] exposes the registration purpose with semantic headings and form", async ({ page }) => { await expect(page.getByRole("heading", { name: /register|create.*account|sign up/i }).first()).toBeVisible(); await expect(page.locator("form")).toHaveCount(1); await expect(submit(page)).toBeVisible(); });
test("[Structure and accessibility] associates accessible labels with every data field", async ({ page }) => { for (const control of [username(page), email(page), dateOfBirth(page), password(page), confirmation(page)]) await expect(control).toBeVisible(); });
test("[Structure and accessibility] uses suitable input types", async ({ page }) => { await expect(email(page)).toHaveAttribute("type", "email"); await expect(dateOfBirth(page)).toHaveAttribute("type", "date"); await expect(password(page)).toHaveAttribute("type", "password"); await expect(confirmation(page)).toHaveAttribute("type", "password"); });
test("[Structure and accessibility] provides useful autocomplete metadata", async ({ page }) => { await expect(username(page)).toHaveAttribute("autocomplete", /username/i); await expect(email(page)).toHaveAttribute("autocomplete", /email/i); await expect(dateOfBirth(page)).toHaveAttribute("autocomplete", /bday/i); await expect(password(page)).toHaveAttribute("autocomplete", /new-password/i); });
test("[Structure and accessibility] provides accessible terms and password visibility controls", async ({ page }) => { await expect(terms(page)).toBeVisible(); await expect(toggle(page)).toBeVisible(); });
test("[Structure and accessibility] associates visible explanations with invalid controls", async ({ page }) => { await fillValid(page); await username(page).fill(""); await submit(page).click(); await expectFieldError(username(page)); });
test("[Structure and accessibility] exposes important feedback through live or alert semantics", async ({ page }) => { await submit(page).click(); await expect(page.locator('[role="alert"], [role="status"], [aria-live]').filter({ hasText: /\S/ }).first()).toBeVisible(); });
test("[Structure and accessibility] shows an error summary when submission has problems", async ({ page }) => { await submit(page).click(); await expect(page.locator('[role="alert"]').filter({ hasText: /correct|problem|error|invalid|required/i }).first()).toBeVisible(); });
test("[Structure and accessibility] focuses the first invalid control after submission", async ({ page }) => { await submit(page).click(); await expect(username(page)).toBeFocused(); });

test("[Form validation] reports all missing requirements in one submission", async ({ page }) => { await submit(page).click(); for (const control of [username(page), email(page), password(page), confirmation(page), terms(page)]) await expectFieldError(control); await expect(page.getByText(/correct|problem|error|invalid|required/i).first()).toBeVisible(); });
test("[Form validation] accepts username length and character boundaries", async ({ page }) => { for (const value of ["Ab3", `A${"b".repeat(19)}`]) { await fillValid(page, { username: value, email: `${value.toLowerCase()}@example.com` }); await submit(page).click(); await expectSuccess(page); await page.reload(); } });
test("[Form validation] rejects usernames outside the public format", async ({ page }) => { for (const value of ["Ab", `A${"b".repeat(20)}`, "1alice", "alice-name", "alice name"]) { await fillValid(page, { username: value }); await submit(page).click(); await expectFieldError(username(page)); } });
test("[Form validation] rejects clearly malformed email addresses", async ({ page }) => { for (const value of ["plainaddress", "two@@example.com", "a b@example.com", ".leading@example.com", "double..dot@example.com", "user@-example.com", "user@example"]) { await fillValid(page, { email: value }); await submit(page).click(); await expectFieldError(email(page)); } });
test("[Form validation] enforces password length, character rules, and exact confirmation", async ({ page }) => { for (const value of ["Short9", "1234567890", "abcdefghij"]) { await fillValid(page, { password: value }); await confirmation(page).fill(value); await submit(page).click(); await expectFieldError(password(page)); } await fillValid(page); await confirmation(page).fill("CoursePass8"); await submit(page).click(); await expectFieldError(confirmation(page)); });
test("[Form validation] accepts a real optional date and requires terms", async ({ page }) => { await fillValid(page); await terms(page).uncheck(); await submit(page).click(); await expectFieldError(terms(page)); await terms(page).check(); await submit(page).click(); await expectSuccess(page); });
test("[Form validation] trims and normalizes identity input", async ({ page }) => { await fillValid(page, { username: "  Trimmed_User  ", email: "  Trimmed.User@Example.COM  " }); await submit(page).click(); await expectSuccess(page); });
test("[Form validation] accepts a password at the maximum length", async ({ page }) => { const value = `${"a".repeat(62)}9Z`; await fillValid(page, { password: value }); await confirmation(page).fill(value); await submit(page).click(); await expectSuccess(page); });
test("[Form validation] allows the optional date of birth to remain empty", async ({ page }) => { await fillValid(page); await dateOfBirth(page).fill(""); await submit(page).click(); await expectSuccess(page); });

test("[Interaction and state] reveals and hides both password fields", async ({ page }) => { await password(page).fill(validUser.password); await confirmation(page).fill(validUser.password); await toggle(page).click(); await expect(password(page)).toHaveAttribute("type", "text"); await expect(confirmation(page)).toHaveAttribute("type", "text"); await toggle(page).click(); await expect(password(page)).toHaveAttribute("type", "password"); await expect(confirmation(page)).toHaveAttribute("type", "password"); });
test("[Interaction and state] completes valid registration with readable success feedback", async ({ page }) => { await fillValid(page); await submit(page).click(); await expectSuccess(page); });
test("[Interaction and state] saves normalized public details", async ({ page }) => { await fillValid(page, { username: "  Stored_User  ", email: "  Stored.User@Example.COM  " }); await submit(page).click(); await expectSuccess(page); const stored = await page.evaluate(() => JSON.stringify(localStorage)); expect(stored).toContain("Stored_User"); expect(stored).toContain("stored.user@example.com"); });
test("[Interaction and state] rejects a case-insensitive username duplicate after reload", async ({ page }) => { await fillValid(page, { username: "Case_User" }); await submit(page).click(); await expectSuccess(page); await page.reload(); await fillValid(page, { username: "  case_user  ", email: "another@example.com" }); await submit(page).click(); await expectFieldError(username(page)); });
test("[Interaction and state] rejects a normalized email duplicate after reload", async ({ page }) => { await fillValid(page, { email: "Mixed.Case@Example.com" }); await submit(page).click(); await expectSuccess(page); await page.reload(); await fillValid(page, { username: "Another_User", email: "  MIXED.CASE@EXAMPLE.COM  " }); await submit(page).click(); await expectFieldError(email(page)); });
test("[Interaction and state] does not reserve details from a rejected attempt", async ({ page }) => { await fillValid(page); await confirmation(page).fill("wrong-value"); await submit(page).click(); await confirmation(page).fill(validUser.password); await submit(page).click(); await expectSuccess(page); });
test("[Interaction and state] never stores either password field", async ({ page }) => { const secret = "UniqueSecret9"; await fillValid(page, { password: secret }); await confirmation(page).fill(secret); await submit(page).click(); await expectSuccess(page); const stored = await page.evaluate(() => JSON.stringify(localStorage)); expect(stored).not.toContain(secret); expect(stored.toLowerCase()).not.toContain("password"); });
test("[Interaction and state] updates the password visibility control's accessible action", async ({ page }) => { await expect(toggle(page)).toHaveAccessibleName(/show.*password/i); await toggle(page).click(); await expect(toggle(page)).toHaveAccessibleName(/hide.*password/i); });
test("[Interaction and state] clears stale field errors after corrected submission", async ({ page }) => { await fillValid(page); const baselineIds = (await username(page).getAttribute("aria-describedby") ?? "").split(/\s+/).filter(Boolean); const baselineText = new Map(await Promise.all(baselineIds.map(async id => [id, (await page.locator(`#${id}`).textContent())?.trim() ?? ""] as const))); await username(page).fill("?"); await submit(page).click(); await expectFieldError(username(page)); const invalidIds = (await username(page).getAttribute("aria-describedby") ?? "").split(/\s+/).filter(Boolean); const dynamicErrorIds: string[] = []; for (const id of invalidIds) { const text = (await page.locator(`#${id}`).textContent())?.trim() ?? ""; if (text && !baselineText.get(id)) dynamicErrorIds.push(id); } expect(dynamicErrorIds.length).toBeGreaterThan(0); await username(page).fill(validUser.username); await submit(page).click(); await expectSuccess(page); await expect(username(page)).not.toHaveAttribute("aria-invalid", "true"); const correctedIds = new Set((await username(page).getAttribute("aria-describedby") ?? "").split(/\s+/).filter(Boolean)); for (const id of dynamicErrorIds) { const error = page.locator(`#${id}`); const cleared = !correctedIds.has(id) || await error.count() === 0 || !(await error.isVisible()) || !(await error.textContent())?.trim(); expect(cleared).toBe(true); } });
test("[Interaction and state] remembers multiple distinct successful accounts", async ({ page }) => { await fillValid(page); await submit(page).click(); await page.reload(); await fillValid(page, { username: "Second_User", email: "second@example.com" }); await submit(page).click(); await expectSuccess(page); const stored = await page.evaluate(() => JSON.stringify(localStorage)); expect(stored).toContain(validUser.username); expect(stored).toContain("Second_User"); });

test("[Stable visual requirements] presents a full-width dark-blue header", async ({ page }) => { const result = await page.locator("header").evaluate(element => { const rect = element.getBoundingClientRect(); const [r=0,g=0,b=0] = getComputedStyle(element).backgroundColor.match(/\d+/g)?.map(Number) ?? []; return { top: rect.top, width: rect.width, viewport: document.documentElement.clientWidth, blue: b > r * 1.25 && b > g * 1.05 }; }); expect(result.top).toBeLessThanOrEqual(1); expect(result.width).toBeGreaterThanOrEqual(result.viewport - 2); expect(result.blue).toBe(true); });
test("[Stable visual requirements] uses a pale background around a centered white panel", async ({ page }) => { const result = await page.locator("form").evaluate(form => { let element: Element | null = form; let white = false; while (element && element !== document.body) { const color = getComputedStyle(element).backgroundColor.replaceAll(" ", ""); if (color === "rgb(255,255,255)" || color === "rgba(255,255,255,1)") white = true; element = element.parentElement; } const body = getComputedStyle(document.body).backgroundColor; const rect = form.getBoundingClientRect(); return { white, body, centerDelta: Math.abs((rect.left + rect.right) / 2 - innerWidth / 2) }; }); expect(result.white).toBe(true); expect(result.body).not.toBe("rgb(255, 255, 255)"); expect(result.centerDelta).toBeLessThan(30); });
test("[Stable visual requirements] uses a restrained orange accent and primary action", async ({ page }) => { const orange = (color: string) => { const [r=0,g=0,b=0] = color.match(/\d+/g)?.map(Number) ?? []; return r >= 160 && g >= 50 && g <= 190 && b <= 120 && r > g + 30; }; const buttonColor = await submit(page).evaluate(element => getComputedStyle(element).backgroundColor); const anyOrange = await page.locator("body *").evaluateAll(elements => elements.some(element => [getComputedStyle(element).color, getComputedStyle(element).backgroundColor, getComputedStyle(element).borderColor].some(color => { const [r=0,g=0,b=0] = color.match(/\d+/g)?.map(Number) ?? []; return r >= 160 && g >= 50 && g <= 190 && b <= 120 && r > g + 30; }))); expect(orange(buttonColor)).toBe(true); expect(anyOrange).toBe(true); });
test("[Stable visual requirements] provides a clearly visible keyboard focus indicator", async ({ page }) => { await username(page).focus(); const style = await username(page).evaluate(element => { const value = getComputedStyle(element); return { outline: value.outlineStyle, outlineWidth: parseFloat(value.outlineWidth), shadow: value.boxShadow }; }); expect(style.outline !== "none" && style.outlineWidth >= 2 || style.shadow !== "none").toBe(true); });
test("[Stable visual requirements] shows error and success states with text rather than color alone", async ({ page }) => { await submit(page).click(); await expect(page.getByText(/correct|problem|error|required|enter|must/i).first()).toBeVisible(); await page.reload(); await fillValid(page); await submit(page).click(); await expectSuccess(page); });
test("[Stable visual requirements] remains operable without horizontal scrolling at 375 pixels", async ({ page }) => { await page.setViewportSize({ width: 375, height: 700 }); await expect(submit(page)).toBeVisible(); const metrics = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: document.documentElement.scrollWidth })); expect(metrics.content).toBeLessThanOrEqual(metrics.viewport + 1); const box = await submit(page).boundingBox(); expect(box!.x).toBeGreaterThanOrEqual(0); expect(box!.x + box!.width).toBeLessThanOrEqual(376); });
test("[Stable visual requirements] positions labels above their text controls", async ({ page }) => { for (const control of [username(page), email(page), password(page), confirmation(page)]) { const id = await control.getAttribute("id"); expect(id).toBeTruthy(); const label = page.locator(`label[for="${id}"]`); const [labelBox, inputBox] = await Promise.all([label.boundingBox(), control.boundingBox()]); expect(labelBox).not.toBeNull(); expect(inputBox).not.toBeNull(); expect(labelBox!.y).toBeLessThan(inputBox!.y); } });
test("[Stable visual requirements] changes related desktop fields to one column on a narrow screen", async ({ page }) => { await page.setViewportSize({ width: 375, height: 900 }); const [first, second] = await Promise.all([username(page).boundingBox(), email(page).boundingBox()]); expect(first).not.toBeNull(); expect(second).not.toBeNull(); expect(Math.abs(first!.x - second!.x)).toBeLessThan(4); expect(second!.y).toBeGreaterThan(first!.y + first!.height); });
